feat: AfreecaTV -> Soop 리브랜딩 대응 및 로거 개선
taromati/done-connector pull request #8
Opened 2024-11-02 04:00 UTC by pangin

타로님 안녕하세요.
작업하신 플러그인에 대해 아래와 같이 기여 해보았습니다.

- 아프리카 TV -> Soop 리브랜딩 대응
- 로거 개선
    - warn 추가
    - error 추가
    - debug 추가*
- 로컬 개발 환경에서 Bukkit 없이 동작 할 수 있도록 수정 (try catch 구문 추가)*

* debug 기능은 Doneconnector의 debug 플래그를 기준으로 동작

감사합니다.

2024-11-02 06:35 UTC, taromati requested changes

2024-11-02 06:35 UTC, taromati commented on build.gradle
안쓰는건 삭제

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Application.java
쓸데없는 Diff 제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +        if (!sender.isOp()) {
! 제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopApi.java
> +            if (!builder.isEmpty()) {
! 제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
띄어쓰기 제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +            Logger.debug(this.getConfig().getConfigurationSection("숲").getKeys(false).toString());
키값에 아프리카 호환 추가

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
> +            System.out.println(fullMsg);
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
> +            System.err.println(prefix + msg);
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
> +            System.out.println(prefix + msg);
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
> +            System.out.println(prefix + ChatColor.LIGHT_PURPLE + msg);
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
> +            System.out.println(command);
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +                Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] 도네이션 아님");
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopWebSocket.java
> +            Logger.error(ChatColor.RED + "[SoopWebsocket][" + soopUser.get("nickname") + "] 숲 메시지 파싱 중 오류가 발생했습니다.");
컬러 중복

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopWebSocket.java
> +            System.out.println("onError: " + ex.getMessage());
제거

2024-11-02 06:35 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopApi.java
> +            // 아래 내용 없어도 라이브 정보 받아 올 수 있음
확실히 안쓰는건지 확인 및 웹과 동일하게 맞춰야함

2024-11-03 09:16 UTC, pangin commented on src/main/java/me/taromati/doneconnector/soop/SoopApi.java
> +            // 아래 내용 없어도 라이브 정보 받아 올 수 있음
bno는 liveinfo API 호출 전에 알아 낼 방법이 없는 것으로 보여 보내지 않는 것이 좋아 보입니다.
우선 해당 항목 제외하고 나머지 웹과 동일하게 맞추겠습니다.

2024-11-04 00:17 UTC, taromati requested changes

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Application.java
파일 통째로 롤백

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/Logger.java
if (DoneConnector.debug) {
             System.out.println(fullMsg);
}
전부 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +            Logger.debug(ChatColor.WHITE + "치지직 아이디 로드 중...");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
엔터 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
엔터 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
엔터 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
엔터 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +                Logger.debug(ChatColor.WHITE + "치지직 닉네임: " + nickname);
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +                Logger.debug(ChatColor.WHITE + "치지직 아이디: " + id);
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +
엔터 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +                Logger.debug(ChatColor.WHITE + "치지직 마크닉네임: " + tag);
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +                Logger.debug(ChatColor.WHITE + "치지직 유저: " + userMap.toString());
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +            Logger.debug(ChatColor.WHITE + "숲 아이디 로드 중...");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +            Logger.debug(this.getConfig().getConfigurationSection("숲").getKeys(false).toString());
이거 반영 안됨

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/DoneConnector.java
> +                        Logger.warn(ChatColor.YELLOW + "닉네임을 찾을 수 없습니다.");
컬러코드

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +        Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] onMessage: " + message);
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +            Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] 파싱 시작");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +                Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] ping");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +                Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] pong");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +            Logger.debug(ChatColor.WHITE + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] 파싱 완료");
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +            Logger.error(ChatColor.RED + "[ChzzkWebsocket][" + chzzkUser.get("nickname") + "] 치지직 메시지 파싱 중 오류가 발생했습니다.");
컬러코드

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/chzzk/ChzzkWebSocket.java
> +            Logger.debug(ChatColor.LIGHT_PURPLE + e.toString());
컬러코드

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopApi.java
> +//            bno를 바로 가져올 수 없기 때문에 보내지 않는 것이 좋아보임
주석 제거

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopApi.java
> +            HttpRequest.BodyPublisher formData = ofFormData(bodyJson);
변수로 분리한 이유 없으면 롤백

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopWebSocket.java
> +                    Logger.info(ChatColor.RED + "숲 웹소켓 핑 스레드가 종료되었습니다.");
info 인지 error인지 컬러코드 확실히

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopWebSocket.java
> +        Logger.debug(ChatColor.WHITE + "[SoopWebSocket][" + soopUser.get("nickname") + "] onMessage: " + new String(bytes.array(), StandardCharsets.UTF_8));
debug인지 info인지 컬러코드랑 같이 확실히 처리

2024-11-04 00:17 UTC, taromati commented on src/main/java/me/taromati/doneconnector/soop/SoopWebSocket.java
> +    public void onError(Exception ex) {}
주석 복구

2024-11-04 03:58 UTC, taromati approved these changes

2024-11-04 03:58 UTC, merged